all:
  hosts:
    master:
      ansible_host: 192.168.11.150
      ansible_port: 22
      ansible_user: vagrant
      ansible_password: vagrant
    slave:
      ansible_host: 192.168.11.151
      ansible_port: 22
      ansible_user: vagrant
      ansible_password: vagrant
